### PR TITLE
Fix disabled and selected days on ResourceCalendar

### LINKED ISSUE #591: Resource calendar previous day should not be available
calendar-yesterday

### PR DESCRIPTION
**Pull request by YoYuUm**
Closes #591

### CODE REVIEW

File: app/shared/resource-calendar/ResourceCalendar.js [hunk 1]
```diff
@@ -22,10 +21,13 @@ export function UnconnectedResourceCalendar({
   selectedDate,
   t,
 }) {
+  const selectedDateArray = selectedDate.split('-');
```
Comment (lraivio) [inline app/shared/resource-calendar/ResourceCalendar.js]: - [ ] This could be `const [year, month, dayNumber] = selectedDate.split('-');`

Then `selectedDay.setFullYear(selectedDateArray[0], selectedDateArray[1] - 1, selectedDateArray[2]);`
would become much more readable:
`selectedDay.setFullYear(year, month - 1, dayNumber);`.
